# Makefile.include
# Platform-dependent settings for HW1
#

CC = pgcc
#CC = gcc

#COPTFLAGS = -O2
COPTFLAGS = -g

CPPFLAGS = 

#CFLAGS = $(COPTFLAGS)
CFLAGS = $(COPTFLAGS)

LINKER = pgcc
#LINKER = gcc

LDFLAGS = -lm -lpthread


