# Makefile.include
# Platform-dependent settings for HW1
#

CC = gcc
#CC = gcc

#COPTFLAGS = -O2
COPTFLAGS = -g

CPPFLAGS = 

#CFLAGS = $(COPTFLAGS)
CFLAGS = -Wall $(COPTFLAGS)

LINKER = gcc
#LINKER = gcc

LDFLAGS = -lm -lpthread


